# [Mensajes de discord]
#
# Mensaje a enviar / editar cuando se inicie el servidor
serverStarted = "Servidor iniciado :white_check_mark:"
# Mensaje a mostrar mientras se inicia el servidor
# Este mensaje será editado a lo que diga en "serverStarted" cuando no se usen webhooks
serverStarting = "Iniciando servidor :clock1:"
# Mensaje a enviar cuando se detenga el servidor
serverStopped = "Servidor apagado"
# Mensaje a mostrar cuando el bot haya detectado que el servidor ha crasheado
serverCrash = "El servidor ha crasheado :warning:"

# [Mensajes de discord a minecraft]
#
# Así se verán los mensajes del chat de discord dentro del juego
# PLACEHOLDERS:
# %user% - Nombre del usuario
# %id% - ID del usuario
# %msg% - Mensaje
ingame_discordMessage = "§6[§#5865F2DISCORD§6]§r <%user%> %msg%"
# Así se verán los mensajes cuando alguien responda un mensaje del chat de discord dentro del juego
# PLACEHOLDERS:
# %user% - Nombre del usuario
# %id% - ID del usuario
# %msg% - Mensaje
# %ruser% - Nombre del usuario al que están respondiendo
# %rmsg% - El mensaje al que están respondiendo
ingame_discordReplyMessage = "§6[§#5865F2DISCORD§6]§r §a%user%§r respondió a §3%ruser%§r: %msg%"
# Lo que se muestra al colocar el mouse sobre el nombre de usuario de un mensaje de discord
# PLACEHOLDERS:
# %user% - Nombre del usuario (Persona123)
# %user#tag% - Discriminador del usuario (@usuario o Usuario#0001)
# %id% - ID del usuario
# NOTE: si usas "@" es probable que suene un ping dentro del juego
discordUserHover = "§3Usuario en discord: %user%\n§aHaz click aquí para mencionar"
# Mensaje a enviar a un jugador cuando su mensaje reciba una reacción
# PLACEHOLDERS:
# %name% - Apodo / nombre del usuario que ha reaccionado
# %name2% - Discriminador del usuario que ha reaccionado (Usuario#0001)
# %msg% - El mensaje que recibió la reacción
# %emote% - Emote reaccionado
reactionMessage = "§6[§#5865F2DISCORD§6]§r§7 %name% ha reaccionado con '%emote%' a \"§9%msg%§7\""
# Texto a mostrar para archivos
attachment = "Archivo"
# Texto a mostrar para stickers
sticker = "Sticker"
# Encabezado de embeds
embed = "Embed"
# Texto a mostrar para imágenes
embedImage = "Imagen"
# Texto a mostrar para mensajes de embeds
embedMessage = "Mensaje"
# Texto a mostrar al colocar el mouse sobre una tag de bot
bot = "Este usuario es un bot"

# [Mensajes de minecraft a discord]
#
# Mensaje a mostrar en discord cuando alguien chatea dentro del juego
# PLACEHOLDERS:
# %player% - Nombre del juagdor
# %msg% - Texto del mensaje
discordChatMessage = "\<%player%\> %msg%"
# Mensaje a enviar cuando un jugador entre al juego
# PLACEHOLDERS:
# %player% - Nombre del jugador
playerJoin = "%player% se ha unido"
# Mensaje a enviar cuando un jugador sale del juego
# PLACEHOLDERS:
# %player% - Nombre del jugador
playerLeave = "%player% se ha ido"
# Mensaje a enviar cuando un jugador muere
# PLACEHOLDERS:
# %player% - Nombre del jugador
# %msg% - El mensaje de muerte
playerDeath = "%player% %msg%"
# Mensaje a enviar cuando un jugador se desconecta por problemas de conexión
# PLACEHOLDERS:
# %player% - Nombre del jugador
playerTimeout = "%player% se ha desconectado por un error"
# Mensaje a enviar cuando un jugador finishes an advancement
# Se pueden colocar nuevas líneas usando \n
# PLACEHOLDERS:
# %player% - Nombre del jugador
# %advName% - Nombre del progreso / logro
# %advDesc% - Descripción del progreso / logro
advancementMessage = "%player% ha conseguido el progreso **[%advName%]**\n_%advDesc%_"

# Textos usados en los comandos de discord
[commands]
  # Se muestra al ejecutar un comando exclusivo del juego en la consola
  ingameOnly = "Este comando solo puede ejecutarse dentro del juego"
  # Se muestra al ejecutar un comando exclusivo de la consola dentro del juego
  consoleOnly = "Este comando solo puede ejecutarse desde la consola"
  # Se muestra cuando se recarga el archivo de configuración correctamente
  configReloaded = "Se ha recargado la configuración"
  # Se muestra cuando un subcomando está deshabilitado
  subcommandDisabled = "Este subcomando está deshabilitado"
  # Se muestra cuando el usuario no tiene permisos suficientes para ejecutar un comando
  noPermission = "No tienes permiso para usar este comando"
  # Se muestra cuando se intenta ejecutar un comando invalido / mal escrito
  unknownCommand = "Comando desconocido, usa `/help` para ver una lista de comandos"
  # Se muestra cuando un jugador no coloca todos los argumentos necesarios
  notEnoughArguments = "Comando incompleto, faltan argumentos"
  # Se muestra cuando un jugador coloca mas argumentos de los necesarios
  tooManyArguments = "Comando invalido, demasiados argumentos"
  # Se muestra cuando no se encuentra al jugador mencionado en un comando
  # PLACEHOLDERS:
  # %player% - Nombre del jugador
  playerNotFound = "No se encontró al jugador \"%player%\""
  # Se muestra al usar 'list' cuando no hay jugadores conectados
  cmdList_empty = "Nadie está conectado"
  # Se muestra en el encabezado de 'list' cuando hay 1 solo jugador conectado
  cmdList_one = "Hay 1 jugador conectado:"
  # El encabezado del comando 'list'
  # PLACEHOLDERS:
  # %amount% - Cantidad de jugadores conectados
  cmdList_header = "Hay %amount% jugadores conectados:"
  # El encabezado del comando 'help'
  cmdHelp_header = "Comandos disponibles en este canal:"
  # Se muestra al empezar a ignorar mensajes de discord dentro del juego
  commandIgnore_ignore = "Ahora estas ignorando mensajes de discord"
  # Se muestra al dejar a ignorar mensajes de discord dentro del juego
  commandIgnore_unignore = "Ya no estas ignorando mensajes de discord"
  # Mensaje a enviar al usar el comando 'uptime'
  # PLACEHOLDERS:
  # %uptime% - El tiempo que el servidor ha estado activo en formato uptime, véase uptimeFormat
  cmdUptime_message = "El servidor a estado funcionando por %uptime%"
  # El formato de uptime
  # Para mas información acerca del formato visite https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.html
  uptimeFormat = "dd 'días' HH 'horas' mm 'minutos'"
  # Se muestra como respuesta al ejecutar slash commands
  executing = "Ejecutando..."
  # Descripción para la opcion 'discorduser' del comando 'linkcheck'
  cmdLinkcheck_userargDesc = "El usuario de discord a comprobar"
  # Descripción para la opcion 'mcplayer' del comando 'linkcheck'
  cmdLinkcheck_mcargDesc = "El nombre o UUID de minecraft a comprobar"
  # Se muestra cuando no hay cuenta vinculada al comprobar
  cmdLinkcheck_notlinked = "Esta cuenta no está vinculada"
  # 
  cmdLinkcheck_discordAcc = "Cuenta de Discord: "
  cmdLinkcheck_minecraftAcc = "Cuenta de Minecraft: "
  cmdLinkcheck_minecraftAccFloodgate = "Minecraft (Bedrock) UUID: "
  cmdLinkcheck_cannotGetPlayer = "Error al obtener información del jugador. Quizas usaste un nombre / UUID invalido?"
  cmdSett_key = "Opción a cambiar"
  cmdSett_val = "Valor a establecer"
  cmdSett_set = "Cambia una opción"
  cmdSett_get = "Obtén el valor de una opción"

    # Descripciones de comandos
    [commands.descriptions]
      settings = "Te permite editar tus opciones personales"
      uptime = "Muestra el tiempo que el servidor estuvo activo"
      help = "Muestra una lista de todos los comandos"
      list = "Muestra a todos los jugadores conectados"
      link = "Vincula tu cuenta de discord con tu cuenta de minecraft"
      whitelist = "Te agrega a la lista blanca del servidor al vincular tu cuenta de discord"
      linkcheck = "Muestra información acerca de una cuenta vinculada de discord / minecraft"

# Strings about the account linking feature
[linking]
  # Sent to the user when he linked his discord successfully
  # PLACEHOLDERS:
  # %player% - The in-game player name
  linkSuccessful = "Your account is now linked with %player%.\nUse /settings to view and set some user-specific settings"
  # Sent to the user when linking fails
  linkFailed = "Account link failed"
  # Sent when an already linked user attempts to link an account
  # PLACEHOLDERS:
  # %player% - The in-game player name
  alreadyLinked = "Your account is already linked with %player%"
  # Sent when attempting to use personal commands while not linked
  # PLACEHOLDERS:
  # %method% - The currently enabled method for linking
  notLinked = "Your account is not linked! Link it first using %method%"
  # Message of the link method in whitelist mode
  # Used by %method% placeholder
  linkMethodWhitelistCode = "joining the server and then using `/link <whitelist-code>` here"
  # Message of the link method in normal mode
  # Used by %method% placeholder
  linkMethodIngame = "`/discord link` ingame"
  # Sent when attempting to whitelist-link with an non uuid string
  # PLACEHOLDERS:
  # %arg% - The provided argument
  link_argumentNotUUID = "Argument \"%arg%\" is not an valid UUID or Name."
  # Sent when attempting to link with an unknown number
  invalidLinkNumber = "Invalid link number!"
  # Sent when attempting to link with an invalid number
  linkNumberNAN = "This is not a number!"
  # Message shown to players who are not whitelisted using discord
  # No effect if discord whitelist is off
  notWhitelistedCode = "§cYou are not whitelisted.\nJoin the discord server for more information\nhttps://discord.gg/someserver\nYour Whitelist-Code is: §6%code%"
  # Message shown to players who are whitelisted using discord but don't have the required role anymore
  # No effect if discord whitelist is off
  notWhitelistedRole = "§cYou are whitelisted, but you need an role to join.\nSee the discord server for more information"
  # Sent when trying to link without an required role
  link_requiredRole = "You need to have an role to use this"
  # Sent when trying to link as an non-member
  link_notMember = "You are not member of the Discord-Server this bot is operating in!"
  # Sent to the user when he linked his discord successfully
  # PLACEHOLDERS:
  # %name% - The linked discord name
  # %name#tag% - The linked discord name with tag
  linkSuccessfulIngame = "Your account is now linked with discord-user %name#tag%"
  # Message shown to players who want to link their discord account ingame
  # 
  # PLACEHOLDERS:
  # %num% - The link number
  linkMsgIngame = "Send this command to the server channel to link your account: /link %num%\nThis number will expire after 10 minutes"
  # Shown when hovering over the link message
  hoverMsg_copyClipboard = "Click to copy command to clipboard"

# Strings about the personal settings feature
[personalSettings]
  # Message for getting an setting's value
  personalSettingGet = "This settings value is `%bool%`"
  # Sent when user sucessfully updates an prersonal setting
  settingUpdateSuccessful = "Successfully updated setting!"
  # Header of the personal settings list
  personalSettingsHeader = "Personal Settings list:"
  # Error message when providing an invalid personal setting name
  invalidPersonalSettingKey = "`%key%` is not an valid setting!"
  settingsCommandUsage = "Usages:\n\n/settings - lists all available keys\n/settings get <key> - Gets the current settings value\n/settings set <key> <value> - Sets an Settings value"
  # Sent when setting an personal setting fails
  settingUpdateFailed = "Failed to set value :/"
  # Sent when attempting to change an blacklisted setting
  settingUpdateBlocked = "The server owner disabled changing of this setting"

    # Descriptions of the settings
    [personalSettings.descriptons]
      ignoreDiscordChatIngame = "Configure if you want to ignore discord chat ingame"
      useDiscordNameInChannel = "Should the bot send messages using your discord name and avatar instead of your in-game name and skin?"
      ignoreReactions = "Configure if you want to ignore discord reactions ingame"
      pingSound = "Toggle the ingame ping sound"
      hideFromDiscord = "Setting this to true will hide all of your minecraft messages from discord"
