# ボットのチャンネルに誰かが入力した場合、ゲーム内で表示される内容
# PLACEHOLDERS:
# %user% - ユーザー名
# %id% - ユーザーID
# %msg% - メッセージ
ingame_discordMessage = "§6[§5DISCORD§6]§r <%user%> %msg%"
# ボットのチャンネルに返信が送信された場合、ゲーム内に表示される内容
# PLACEHOLDERS:
# %user% - ユーザー名
# %id% - ユーザーID
# %msg% - 返信メッセージ
# %ruser% - 返信先のメッセージのユーザー名
# %rmsg% - 返信先のメッセージ
ingame_discordReplyMessage = "§6[§5DISCORD§6]§r §a%user%§r が §3%ruser%§r に返信しました: %msg%"
# Discordメッセージのユーザー名をホバーすると表示されるメッセージ
# PLACEHOLDERS:
# %user% - ユーザー名/ニックネーム（例: Someone123）
# %user#tag% - タグ付きのユーザー名（例: someone#0001）
# %id% - ユーザーID
#
# 注意：ここで@を使用すると、ゲーム内でピン音が鳴る場合があります
discordUserHover = "§3Discordユーザー %user#tag%\n§aクリックしてメンション"
# サーバーが起動し終わった際に編集される/送信されるメッセージ
serverStarted = "サーバーが起動しました！"
# サーバーが起動中の場合に表示されるメッセージ
# webhookがfalseの場合はSERVER_STARTED_MSGに編集されます
serverStarting = "サーバーを起動しています..."
# サーバーが停止したときに送信されるメッセージ
serverStopped = "サーバーが停止しました！"
# サーバーがクラッシュした場合に表示されるメッセージ
serverCrash = "サーバーがクラッシュしました :thinking:"
# プレイヤーが参加したときに送信されるメッセージ
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
playerJoin = "%player% が参加しました"
# プレイヤーが退出したときに送信されます
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
playerLeave = "%player% が退出しました"
# プレイヤーが死亡したときに送信されます
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
# %msg% - 死亡メッセージ
playerDeath = "%player% %msg%"
# プレイヤーがタイムアウトした場合に送信される、playerLeaveの代わりのメッセージです
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
playerTimeout = "%player% はタイムアウトしました！"
# プレイヤーがアドバンスメントを達成したときに送信されます
# \nを使って複数行のメッセージをサポートします
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
# %name% - アドバンスメントの名前
# %desc% - アドバンスメントの説明
advancementMessage = "%player% がアドバンスメント **%name%** を獲得しました\n_%desc%_"
# ゲーム内のプレイヤーから送信されたチャットメッセージ
#
# PLACEHOLDERS:
# %player% - プレイヤーの名前
# %msg% - チャットメッセージ
discordChatMessage = "%player%: %msg%"
# 誰かがメッセージにリアクションしたときにプレイヤーに送信されるメッセージ
# PLACEHOLDERS:
# %name% - リアクションをしたユーザーの名前（フォーマット：'SomeNickName'）
# %name2% - ディスコードの識別子を含めたリアクションしたユーザーの名前（フォーマット：'SomeName#0123'）
# %msg% - リアクションされたメッセージの内容
# %emote% - リアクションされた絵文字
reactionMessage = "§6[§5DISCORD§6]§r§7 %name% が \"§9%msg%§7\" に '%emote%' でリアクションしました"
# 添付ファイル用のメッセージ
attachment = "添付ファイル"
# スタンプ用のメッセージ
sticker = "スタンプ"
# 埋め込み用のヘッダー
embed = "埋め込み"
# 埋め込み画像用のメッセージ
embedImage = "画像"
# 埋め込みメッセージ用のメッセージ
embedMessage = "メッセージ"
# インゲームでのボットのタグに表示されるメッセージ
bot = "このユーザーはボットです"

# Discordのコマンドに関する文字列
[commands]
  # Discordコマンドを使用しようとしたときにコンソールに表示されるメッセージ
  ingameOnly = "このコマンドはゲーム内でのみ実行できます"
  # コンフィグファイルが正常にリロードされたときに表示されるメッセージ
  configReloaded = "Configがリロードされました！"
  # 無効化されたサブコマンドを使用したときに表示されるメッセージ
  subcommandDisabled = "このサブコマンドは無効化されています！"
  # ユーザーがコマンドを実行するための権限を持っていないときに表示されるメッセージ
  noPermission = "このコマンドを実行するための権限がありません！"
  # 無効なコマンドが入力されたときに表示されるメッセージ
  #
  # PLACEHOLDERS:
  unknownCommand = "未知のコマンドです。コマンドのリストを確認するには、`/help`を入力してください"
  # プレイヤーが必要な引数を提供しなかった場合に表示されるメッセージ
  notEnoughArguments = "引数が不足しています"
  # プレイヤーが多すぎる引数を提供した場合に表示されるメッセージ
  tooManyArguments = "引数が多すぎます"
  # プレイヤーが見つからなかった場合に表示されるメッセージ
  #
  # PLACEHOLDERS:
  # %player% - プレイヤーの名前
  playerNotFound = "\"%player%\"というプレイヤーは見つかりません"
  # 'list'コマンドを使用したとき、オンラインのプレイヤーがいない場合のメッセージ
  cmdList_empty = "現在、プレイヤーはいません..."
  # 'list'コマンドを使用したとき、オンラインのプレイヤーが1人いる場合のヘッダー
  cmdList_one = "現在、プレイヤーが1人オンラインです:"
  # 'list'コマンドのヘッダー
  # PLACEHOLDERS:
  # %amount% - オンラインのプレイヤー数
  cmdList_header = "現在、%amount%人のプレイヤーがオンラインです:"
  # ヘルプコマンドのヘッダー
  cmdHelp_header = "このチャンネルで使用可能なコマンド:"
  # Discordメッセージを無視するときに送信されるメッセージ
  commandIgnore_ignore = "Discordのメッセージを無視するように設定しました！"
  # Discordメッセージを無視しないように設定するときに送信されるメッセージ
  commandIgnore_unignore = "Discordのメッセージの無視を解除しました！"
  # 'uptime'コマンドを使用したときに送信されるメッセージ
  #
  # PLACEHOLDERS:
  # %uptime% - uptimeフォーマットでの稼働時間、uptimeFormatを参照してください
  cmdUptime_message = "サーバーは%uptime%稼働しています。"
  # uptimeコマンドのフォーマット
  # フォーマットに関する詳細は、https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/DurationFormatUtils.htmlを参照してください
  uptimeFormat = "dd'日' HH'時' mm'分'"
  # スラッシュコマンドを実行したときに表示されるコマンドレスポンス
  executing = "実行中..."
  # linkcheckコマンドのDiscordユーザーパラメーターのコマンド引数の説明
  cmdLinkcheck_userargDesc = "チェックするDiscordユーザー"
  # linkcheckコマンドのminecraftプレイヤーパラメーターのコマンド引数の説明
  cmdLinkcheck_mcargDesc = "確認するMinecraftプレイヤーのUUIDまたは名前"
  # リンクされていない場合に送信されるメッセージ
  cmdLinkcheck_notlinked = "このアカウントはリンクされていません！"
  #
  cmdLinkcheck_discordAcc = "Discordアカウント: "
  cmdLinkcheck_minecraftAcc = "Minecraftアカウント: "
  cmdLinkcheck_cannotGetPlayer = "プレイヤー情報を取得できませんでした。無効な名前/UUIDを使用した可能性があります。"
  cmdSett_key = "設定のキー"
  cmdSett_val = "設定値"
  cmdSett_set = "設定を変更する"
  cmdSett_get = "設定値を取得する"

    # コマンドの説明
    [commands.descriptions]
      settings = "個人設定を編集できます"
      uptime = "サーバーの稼働時間を表示します"
      help = "全てのコマンドのリストを表示します"
      list = "現在オンライン中のすべてのプレイヤーをリストします"
      link = "DiscordアカウントとMinecraftアカウントをリンクします"
      whitelist = "Discordとリンクしてサーバーのホワイトリストに登録します"
      linkcheck = "リンクされたDiscordユーザーまたはゲーム内プレイヤーの情報を表示します"

# アカウントリンクに関する文字列
[linking]
  # Discordとのリンクが成功した場合にユーザーに送信されるメッセージ
  # PLACEHOLDERS:
  # %player% - ゲーム内のプレイヤー名
  linkSuccessful = "あなたのアカウントは%player%とリンクされました。\n/settingsを使用して、ユーザー固有の設定を表示および設定できます。"
  # リンクに失敗した場合にユーザーに送信されるメッセージ
  linkFailed = "アカウントリンクに失敗しました"
  # すでにリンクされたユーザーがアカウントをリンクしようとした場合に送信されるメッセージ
  # PLACEHOLDERS:
  # %player% - ゲーム内のプレイヤー名
  alreadyLinked = "あなたのアカウントはすでに%player%とリンクされています。"
  # リンクされていない状態で個人コマンドを使用しようとした場合に送信されるメッセージ
  # PLACEHOLDERS:
  # %method% - リンク方法
  notLinked = "あなたのアカウントはリンクされていません！先に%method%を使用してリンクしてください。"
  # ホワイトリストモードでのリンク方法のメッセージ
  # %method%プレースホルダーで使用されます
  linkMethodWhitelistCode = "サーバーに参加してから、ここで`/link <whitelist-code>`を使用してください"
  # 通常モードでのリンク方法のメッセージ
  # %method%プレースホルダーで使用されます
  linkMethodIngame = "ゲーム内で`/discord link`を使用してください"
  # UUID以外の文字列を使用してホワイトリストリンクを試みた場合に送信されるメッセージ
  # PLACEHOLDERS:
  # %arg% - 提供された引数
  link_argumentNotUUID = "引数「%arg%」は有効なUUIDまたは名前ではありません。"
  # 不明な番号でリンクしようとした場合に送信されるメッセージ
  invalidLinkNumber = "無効なリンク番号です！"
  # 無効な番号でリンクしようとした場合に送信されるメッセージ
  linkNumberNAN = "これは数値ではありません！"
  # Discordを使用してホワイトリストに載っていないプレイヤーに表示されるメッセージ
  # Discordホワイトリストがオフの場合は効果がない
  notWhitelistedCode = "§cホワイトリストに載っていません。\n詳細についてはDiscordサーバーに参加してください。\nhttps://discord.gg/someserver\nあなたのホワイトリストコードは：§6%code%"
  # Discordを使用してホワイトリストに載っているが必要な役職がないプレイヤーに表示されるメッセージ
  # Discordホワイトリストがオフの場合は効果がない
  notWhitelistedRole = "§cホワイトリストに載っていますが、参加するためには役職が必要です。\n詳細についてはDiscordサーバーをご確認ください。"
  # 必要な役割がない場合にリンクを試みた場合に送信されるメッセージ
  link_requiredRole = "この操作を行うには、役割を持っている必要があります。"
  # 非メンバーとしてリンクを試みた場合に送信されるメッセージ
  link_notMember = "あなたはこのボットが操作しているDiscordサーバーのメンバーではありません！"
  # Discordとのリンクが成功した場合にユーザーに送信されるメッセージ
  # PLACEHOLDERS:
  # %name% - リンクされたDiscord名
  # %name#tag% - タグを含めたリンクされたDiscord名
  linkSuccessfulIngame = "あなたのアカウントはdiscordユーザー%name#tag%とリンクされました。"
  # ゲーム内でDiscordアカウントをリンクするプレイヤーに表示されるメッセージ
  #
  # PLACEHOLDERS:
  # %num% - リンク番号
  linkMsgIngame = "あなたのアカウントをリンクするには、このコマンドをサーバーチャネルに送信してください: /link %num%\nこの番号は10分後に期限切れになります。"
  # リンクメッセージをホバーしたときに表示されるメッセージ
  hoverMsg_copyClipboard = "クリックしてコマンドをクリップボードにコピー"

# パーソナル設定機能に関する文字列
[personalSettings]
  # 設定の値を取得するためのメッセージ
  personalSettingGet = "この設定の値は `%bool%` です"
  # ユーザーが設定を更新した場合に送信されるメッセージ
  settingUpdateSuccessful = "設定を更新しました！"
  # 個人設定リストのヘッダー
  personalSettingsHeader = "個人設定リスト："
  # 無効な個人設定名が指定された場合のエラーメッセージ
  invalidPersonalSettingKey = "`%key%` は無効な設定です！"
  settingsCommandUsage = "使用法：\n\n/settings - 使用可能なすべてのキーをリスト表示します\n/settings get <key> - 現在の設定値を取得します\n/settings set <key> <value> - 設定値を設定します"
  # 個人設定の設定に失敗した場合に送信されるメッセージ
  settingUpdateFailed = "値の設定に失敗しました :/"
  # ブラックリストされた設定を変更しようとした場合に送信されるメッセージ
  settingUpdateBlocked = "サーバーのオーナーによって、この設定の変更が無効になっています"

    # 設定の説明
    [personalSettings.descriptons]
      ignoreDiscordChatIngame = "ゲーム内でDiscordのチャットを無視するかどうかを設定します"
      useDiscordNameInChannel = "ボットが、あなたのゲーム内の名前とスキンではなく、Discordの名前とアバターを使用してメッセージを送信するかどうかを設定します"
      ignoreReactions = "ゲーム内でDiscordのリアクションを無視するかどうかを設定します"
      pingSound = "ゲーム内のピン音をオン/オフに切り替えます"
      hideFromDiscord = "この設定をtrueにすると、あなたのMinecraftのすべてのメッセージがDiscordから非表示になります"
